### PR TITLE
feat: Add vendor management files and fix package path

### PR DESCRIPTION
**Pull request by gaocegege**
This PR:

- Add go.sum and go.mod for vendor management
- Fix the package path

### CODE REVIEW

**Comment by gaocegege** [comment]
I think we should wait until #6 merged

**Comment by liucimin** [comment]
ehh..
I think add the vendor and change package path is great.
It can merge before update the readme ~

**Comment by gaocegege** [comment]
@liucimin OK, I saw there are some other changes in your README PR, thus it may have conflicts with this PR. Then I think we can merge your PR first.

If #6 only updates readme, we can merge this PR with no worry.

**Comment by liucimin** [comment]
Maybe u can also commit the vendor dir in the pr?



发自我的iPhone


------------------ Original ------------------

**Comment by gaocegege** [comment]
@liucimin I committed the vendor. Please have a look

**Comment by liucimin** [comment]
/LGMT


Would do you check your email?we invited u to the slack to dicuss with us more quickly 



发自我的iPhone


------------------ Original ------------------

**Comment by gaocegege** [comment]
@liucimin 

Thanks, I joined the channel.

**Pull request closed without merging**
